version: '3'

volumes:
  mysql_data:
    driver: local

services:
  db:
    container_name: db_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 3306
      KC_DB_SCHEMA: keycloak
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - db
  php-fpm:
    container_name: app-php
    image: phpdockerio/php:8.2-fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - './php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
  webserver:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '11000:80'
    depends_on:
      - php-fpm
      - keycloak